from .service_analysis import SERVICE_ANALYSIS_PROMPT
from .risk_assessment import RISK_ASSESSMENT_PROMPT
from .improvement import IMPROVEMENT_SUGGESTION_PROMPT, COMPARISON_PROMPT
from .report_generation import REPORT_GENERATION_PROMPT, SUMMARY_PROMPT
