# prompts/__init__.py

from .service_analysis import SERVICE_ANALYSIS_PROMPT
from .risk_assessment import RISK_ASSESSMENT_PROMPT
from .improvement import IMPROVEMENT_SUGGESTION_PROMPT, COMPARISON_PROMPT
from .report_generation import (
    DETAILED_REPORT_GENERATION_PROMPT,
    SUMMARY_GENERATION_PROMPT,
    REPORT_GENERATION_PROMPT
)

__all__ = [
    'SERVICE_ANALYSIS_PROMPT',
    'RISK_ASSESSMENT_PROMPT',
    'IMPROVEMENT_SUGGESTION_PROMPT',
    'COMPARISON_PROMPT',
    'DETAILED_REPORT_GENERATION_PROMPT',
    'SUMMARY_GENERATION_PROMPT',
    'REPORT_GENERATION_PROMPT'
]