from .service_analysis import get_service_analysis_prompt
from .ethics_evaluation import get_ethics_evaluation_prompt
from .improvement_proposal import get_improvement_proposal_prompt
from .report_generation import get_report_generation_prompt